name: "API Upgrade"

on:
  workflow_call:
    inputs:
      api:
        type: string
        description: "API to upgrade"
        required: false

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    name: Upgrade
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      API: ${{ inputs.api || 'api' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run upgrade
        id: upgrade
        run: |
          SCRIPT=${{ inputs.api && format('upgrade-api:{0}', inputs.api) || 'upgrade-api' }}
          echo "Running $SCRIPT"
          VERSION=$(npm run $SCRIPT patch --silent | tail -n 1)
          echo "Upgraded ${{ env.API }} to version $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: Upgrade ${{ env.API }} to ${{ steps.upgrade.outputs.version }}"
          title: "chore: Upgrade ${{ env.API }} to ${{ steps.upgrade.outputs.version }}"
          body: |
            Upgrade ${{ env.API }} to ${{ steps.upgrade.outputs.version }}
          branch: "upgrade-${{env.API}}-${{ steps.upgrade.outputs.version }}"
          base: "main"
