name: Auto-Merge
on:
  workflow_call:

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "enable-auto-merge action has been temporarily disabled"
      #   Disabled as deploys on main were not triggered (https://github.com/orgs/community/discussions/25702)
      #   A workaround could be to use PATs but it's not ideal in terms of security
      #   We could investigate
      #   Also, alexwilson/enable-github-automerge-action@main can be replaced by gh pr merge --squash --auto
      #
      # - uses: alexwilson/enable-github-automerge-action@main
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      #     merge-method: "SQUASH"
      #
