name: Deploy on AWS environmen

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
    secrets:
      AWS_CICD_ROLE:
        required: true
      AWS_CICD_ACCES_KEY:
        required: true
      AWS_CICD_SECRET_KEY:
        required: true

jobs:
  deploy:
    name: Build And Deploy

    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: https://npm.pkg.github.com/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.AWS_CICD_ROLE }}
          role-duration-seconds: 1800
          role-session-name: GitActionDeploymentSession

      - name: Prerequisite Installation
        run: npm install -g aws-cdk

      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Deploy
        run: |
          cd $GITHUB_WORKSPACE
          ls -a
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          GH_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
