name: Synth on PR

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      stack:
        required: false
        type: string
    secrets:
      AWS_CICD_ROLE:
        required: true
      AWS_CICD_ACCESS_KEY:
        required: true
      AWS_CICD_SECRET_KEY:
        required: true

jobs:
  # sast:
  #   name: SAST Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run Report
  #       id: report
  #       uses: bearer/bearer-action@v2
  #       with:
  #         diff: true

  sast:
    name: SAST
    uses: Bastion-Technologies/github_workflows/.github/workflows/sast.yml@main

  build:
    defaults:
      run:
        working-directory: ./cdk

    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: https://npm.pkg.github.com/
      - name: install dependencies
        run: |
          if [ -f "install.sh" ]
            then
                echo "install.sh script found! running it";
                chmod 700 install.sh
                ./install.sh
            else
               echo "install.sh script NOT found! running `npm ci`";
               cd ..;
               npm ci;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache/save@v3
        with:
          path: "**/node_modules/**"
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

  typescript-check:
    name: Typescript checking

    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Build
        uses: actions/cache/restore@v3
        with:
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/node_modules/**"
      - name: Typescript checking
        run: |
          npm run compile --workspaces --if-present;
          if [ $? -ne 0 ]; then
            echo "{check_failed}={true}" >> "$GITHUB_OUTPUT"
          fi
  linter-check:
    name: Linter checking

    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Build
        uses: actions/cache/restore@v3
        with:
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/node_modules/**"
      - name: Linter checking
        run: |
          npm run lint --workspaces --if-present;
          if [ $? -ne 0 ]; then
            echo "{check_failed}={true}" >> "$GITHUB_OUTPUT"
          fi
  list-workspaces:
    name: List workspaces
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Build
        uses: actions/cache/restore@v3
        with:
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/node_modules/**"
      - id: set-matrix
        run: |
          WORKSPACES=$(npm query .workspace | jq -r '.[].location' | jq --raw-input --slurp 'split("\n")' | jq 'del(.[] | select(. == ""))')
          echo 'found workspaces: '$WORKSPACES
          echo "matrix="$WORKSPACES >> $GITHUB_OUTPUT
  test-check:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build, list-workspaces]
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.list-workspaces.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Build
        uses: actions/cache/restore@v3
        with:
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/node_modules/**"
      - name: Run unit tests
        run: |
          npm test -- ${{ matrix.workspace }} --passWithNoTests;
          if [ $? -ne 0 ]; then
            echo "{check_failed}={true}" >> "$GITHUB_OUTPUT"
          fi
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
  synth-check:
    name: CDK Synth
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Build
        uses: actions/cache/restore@v3
        with:
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/node_modules/**"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.AWS_CICD_ROLE }}
          role-duration-seconds: 1800
          role-session-name: GitActionDeploymentSession

      - name: Prerequisite Installation
        run: npm install -g aws-cdk esbuild
      - name: Check cdk synth
        run: |
          cd cdk;
          chmod 700 synth.sh
          ./synth.sh
          if [ $? -ne 0 ]; then
            echo "{check_failed}={true}" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  final-check:
    name: Final check
    runs-on: ubuntu-latest
    if: always()
    needs: [build, typescript-check, linter-check, test-check, synth-check]
    steps:
      - name: echo
        run: |
          if [[ "${{ needs.typescript-check.outputs.check_failed }}" == "true" ]]; then
            exit 1
          fi
          if [[ "${{ needs.linter-check.outputs.check_failed }}" == "true" ]]; then
            exit 1
          fi
          if [[ "${{ needs.test-check.outputs.check_failed }}" == "true" ]]; then
            exit 1
          fi
          if [[ "${{ needs.synth-check.outputs.check_failed }}" == "true" ]]; then
            exit 1
          fi
          echo 'Finished :)'
