name: Check Labels

on: workflow_call

permissions:
  pull-requests: read

jobs:
  check-labels:
    name: Check Labels
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: Do not have do_not_merge label
      run: |
        labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')

        echo "Labels: $labels"

        if echo "$labels" | grep -qE "do_not_merge|do not merge"; then
            echo "PR has do_not_merge label"
            exit 1
        else
          echo "PR does not have do_not_merge label"
        fi
