name: Check if npm package version has changed (run 'npm run upgrade-api <patch|minor|major>')
on:
  workflow_call:
    inputs:
      library-name:
        required: true
        type: string

jobs:
  check-if-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: https://npm.pkg.github.com/

      - name: "current version of library"
        run: 'echo "CURRENT=$(npm version -w=@bastion-technologies/${{ inputs.library-name }} | grep ''@bastion-technologies/${{inputs.library-name}}'')" >> $GITHUB_ENV'
      - run: "git checkout main"
      - name: "main version of library"
        run: 'echo "MAIN=$(npm version -w=@bastion-technologies/${{ inputs.library-name }} | grep ''@bastion-technologies/${{inputs.library-name}}'')" >> $GITHUB_ENV'
      - name: "compare version"
        run: |
          if [ "${{env.MAIN}}" = "${{env.CURRENT}}" ]; then
            echo version did not change main: ${{env.MAIN}}, current: ${{env.CURRENT}};
            echo "::error::Version of ${{ inputs.library-name}} has not been updated" && exit 1;
          fi
