name: SAST

on: workflow_call

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: clone application source code
        uses: actions/checkout@v4
      - name: run sast
        uses: Bastion-Technologies/gh-action-run-sast@v1
