name: Update BT Dependencies

on:
  workflow_call:
    secrets:
      NAUTILUS_SHARED_SECRET:
        required: true

jobs:
  update-bt-dependencies:
    name: Update BT Dependencies
    runs-on: ubuntu-22.04
    # Runs only for merged Dependabot PRs updating a Bastion API
    if: ${{ contains(github.head_ref, 'dependabot') && contains(github.head_ref, 'bastion-technologies') && github.event.pull_request.merged == true }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            :robot: Bastion API upgrade detected, automatically updating BT Dependencies :robot:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - name: Update BT Dependencies
        run: |
          pnpm run nautilus
      - name: Create new branch
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git switch -c ${{ github.head_ref }}-bt-dependencies
          git commit -am "chore: update BT dependencies"
          git push --set-upstream origin ${{ github.head_ref }}-bt-dependencies --force

  pr:
    needs: update-bt-dependencies
    name: Create Pull Request
    uses: Bastion-Technologies/github_workflows/.github/workflows/nautilus-pr.yml@main
    with:
      repo: ${{ github.repository }}
      branch: ${{ github.head_ref }}-bt-dependencies
      base: main
      title: "chore(deps): update BT dependencies for ${{ github.head_ref }}"
      body: ":robot: Bastion API upgrade detected in #${{ github.event.number }}, automatically updating BT Dependencies :robot:"
    secrets:
      NAUTILUS_SHARED_SECRET: ${{ secrets.NAUTILUS_SHARED_SECRET }}